# Generated by Django 5.2.12 on 2026-03-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="body_parts",
        ),
        migrations.RemoveField(
            model_name="workoutset",
            name="is_warmup",
        ),
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutset",
            name="set_type",
            field=models.CharField(
                choices=[
                    ("N", "Normal"),
                    ("W", "Warm-up"),
                    ("D", "Drop Set"),
                    ("F", "Failure"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="performedworkout",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gym_api.workouttemplate",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseBodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_api.bodypart",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muscles",
                        to="gym_api.exercise",
                    ),
                ),
            ],
        ),
    ]
