# Generated by Django 5.2.12 on 2026-03-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0002_remove_exercise_body_parts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_api.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_api.workouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="workouttemplate",
            name="exercises",
            field=models.ManyToManyField(
                through="gym_api.TemplateExercise", to="gym_api.exercise"
            ),
        ),
    ]
