# Generated by Django 5.2.12 on 2026-03-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0003_templateexercise_workouttemplate_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateexercise",
            name="target_reps",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="templateexercise",
            name="target_sets",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="templateexercise",
            name="target_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="templateexercise",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_exercises",
                to="gym_api.workouttemplate",
            ),
        ),
    ]
