# Generated by Django 5.2.12 on 2026-03-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0004_templateexercise_target_reps_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templateexercise",
            options={},
        ),
        migrations.RemoveField(
            model_name="templateexercise",
            name="target_reps",
        ),
        migrations.RemoveField(
            model_name="templateexercise",
            name="target_sets",
        ),
        migrations.RemoveField(
            model_name="templateexercise",
            name="target_weight",
        ),
        migrations.CreateModel(
            name="TemplateSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("target_reps", models.PositiveIntegerField(default=10)),
                ("target_weight", models.FloatField(default=0.0)),
                (
                    "set_type",
                    models.CharField(
                        choices=[
                            ("W", "Warmup"),
                            ("N", "Normal"),
                            ("F", "Failure"),
                            ("D", "Dropset"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "template_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="gym_api.templateexercise",
                    ),
                ),
            ],
        ),
    ]
