# Generated by Django 5.2.12 on 2026-03-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0005_alter_templateexercise_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workouttemplate",
            name="exercises",
        ),
    ]
